engines:
  duplication:
    config:
      languages:
        - php
    enabled: true
  fixme:
    enabled: true
  phpmd:
    checks:
      CleanCode/StaticAccess:
        enabled: false
      Controversial/Superglobals:
        enabled: false
      UnusedPrivateMethod:
        enabled: false
    enabled: true
exclude_paths:
  - tests/
ratings:
  paths:
    - "**.php"
